-- Minimal schema for Petfinder

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(40),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

  -- Extend Pets table to include additional fields
  ALTER TABLE pets
    ADD COLUMN species VARCHAR(50) DEFAULT 'perro',
    ADD COLUMN breed VARCHAR(100) DEFAULT NULL,
    ADD COLUMN color VARCHAR(100) DEFAULT NULL,
    ADD COLUMN notes TEXT DEFAULT NULL,
    ADD COLUMN qr_id VARCHAR(32) NOT NULL UNIQUE,
    ADD COLUMN updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS pets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  owner_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  species VARCHAR(60),
  breed VARCHAR(120),
  color VARCHAR(120),
  qr_id VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(id)
);
